# Generated by Django 2.2.6 on 2019-12-05 13:47

import cogether.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=cogether.utils.avatar_upload_to),
        ),
    ]
