# Generated by Django 2.2.6 on 2020-01-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200113_1756'),
        ('account', '0003_myuser_social_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='like_events',
            field=models.ManyToManyField(to='event.DevEvent'),
        ),
    ]
