# Generated by Django 2.2.6 on 2020-01-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_myuser_like_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='like_events',
            field=models.ManyToManyField(related_name='like_event', to='event.DevEvent'),
        ),
    ]
