# Generated by Django 2.2.6 on 2020-01-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200114_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
