# Generated by Django 2.2.6 on 2019-12-19 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HelpCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('help', 'help'), ('update_request', 'update'), ('create_request', 'create')], default='help', max_length=30)),
                ('type', models.CharField(choices=[('freq', 'frequency-questions'), ('my', 'my-questions')], default='my', max_length=40)),
                ('status', models.CharField(choices=[('freq', 'waiting'), ('my', 'completed')], default='freq', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.CharField(blank=True, max_length=30)),
                ('answer', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
