# Generated by Django 2.2.6 on 2020-02-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_auto_20200118_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture', models.ImageField(upload_to='')),
                ('original_url', models.URLField(unique=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.Question')),
            ],
        ),
    ]
