# Generated by Django 2.2.6 on 2020-02-19 18:24

import cogether.storages
import cogether.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_capture'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(storage=cogether.storages.MediaStorage(), upload_to=cogether.utils.help_image_upload_to)),
            ],
        ),
        migrations.DeleteModel(
            name='Capture',
        ),
    ]
