# Generated by Django 2.2.6 on 2020-01-08 14:48

import cogether.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=cogether.utils.uuid_name_upload_to)),
                ('original_url', models.URLField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='facebookcrawling',
            name='category',
        ),
        migrations.RemoveField(
            model_name='festacrawling',
            name='category',
        ),
        migrations.RemoveField(
            model_name='manualevent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='meetupcrawling',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notdevevent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userrequestevent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='waitingevent',
            name='category',
        ),
        migrations.AddField(
            model_name='devevent',
            name='original_identity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='devevent',
            name='status',
            field=models.CharField(choices=[('development', '개발 관련 행사'), ('not_development', '비개발 관련 행사'), ('unclassified_events', '미분류 행사')], default='unclassified_events', max_length=30),
        ),
        migrations.AlterField(
            model_name='devevent',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Category'),
        ),
        migrations.AlterField(
            model_name='devevent',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Photo'),
        ),
        migrations.AlterField(
            model_name='devevent',
            name='source',
            field=models.CharField(choices=[('manual', '사이트에서 직접 입력'), ('user_request', '사용자 요청'), ('festa_crawling', 'FESTA 크롤링'), ('meetup_crawling', 'MEETUP 크롤링'), ('meetup_crawling', 'EVENTUS 크롤링'), ('facebook_crawling', 'FACEBOOK 크롤링')], default='manual', max_length=30),
        ),
        migrations.DeleteModel(
            name='EventusCrawling',
        ),
        migrations.DeleteModel(
            name='FacebookCrawling',
        ),
        migrations.DeleteModel(
            name='FestaCrawling',
        ),
        migrations.DeleteModel(
            name='ManualEvent',
        ),
        migrations.DeleteModel(
            name='MeetupCrawling',
        ),
        migrations.DeleteModel(
            name='NotDevEvent',
        ),
        migrations.DeleteModel(
            name='UserrequestEvent',
        ),
        migrations.DeleteModel(
            name='WaitingEvent',
        ),
    ]
