# Generated by Django 2.2.6 on 2019-11-16 11:16

import cogether.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20191113_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to=cogether.utils.uuid_name_upload_to),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
