# Generated by Django 2.2.6 on 2020-01-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200113_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devevent',
            name='source',
            field=models.CharField(choices=[('manual', '사이트에서 직접 입력'), ('user_request', '사용자 요청'), ('festa_crawling', 'FESTA 크롤링'), ('meetup_crawling', 'MEETUP 크롤링'), ('eventus_crawling', 'EVENTUS 크롤링'), ('facebook_crawling', 'FACEBOOK 크롤링')], default='manual', max_length=30),
        ),
    ]
